### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by UestcJay** [Runsong123/AdaFit#1]
thanks for your work. 
 I read the code ,have some questions, What does this line of [code](https://github.com/Runsong123/AdaFit/blob/ba4191387830540e40949a09336a358e734f8a55/models/AdaFit_multi_scale.py#L408) mean？

**Comment by Runsong123** [comment]
Hi~ 
We want to keep the query point unchanged, so just set the offset of the query point to (0.0, 0.0, 0.0).
Note that, this code is consistent with the procedure in the inference and we can directly calculate the normal by the original formula since the query point is still equal to the origin point.

**Comment by UestcJay** [comment]
> Hi~ We want to keep the query point unchanged, so just set the offset of the query point to (0.0, 0.0, 0.0). Note that, this code is consistent with the procedure in the inference and we can directly calculate the normal by the original formula since the query point is still equal to the origin point.

thanks for your reply! To reproduce the results in the paper， when  training, the train txt is `trainingset_whitenoise.txt`, or `trainingset_vardensity_whitenoise.txt`?

**Comment by Runsong123** [comment]
> > Hi~ We want to keep the query point unchanged, so just set the offset of the query point to (0.0, 0.0, 0.0). Note that, this code is consistent with the procedure in the inference and we can directly calculate the normal by the original formula since the query point is still equal to the origin point.
> 
> thanks for your reply! To reproduce the results in the paper， when training, the train txt is `trainingset_whitenoise.txt`, or `trainingset_vardensity_whitenoise.txt`?

You should use the 'trainingset_whitenoise.txt' list that is provided in the PCPNet dataset when you train the model.
