### ISSUE TITLE
about real dataset

### ISSUE THREAD

**Issue by nannanshen** [Runsong123/AdaFit#3]
many thanks for your great work! can you release sampleed point cloud and gt_normal from SceneNN dataset  mentioned in the paper?

**Comment by Runsong123** [comment]
Thanks for your interest.
But I found that I did not save the data. If you want to reproduce the result, you can download all the mesh data first (SceneNN dataset), and randomly sample the point cloud and normal. Note that, 
1). the sample number is 1000,000 per scene.
2). we first calculate the RMSE for each scene and then average them.



Best,
Runsong
