### ISSUE TITLE
Multi AdaFit Training： RuntimeError: inconsistent tensors dimensions input: 2 other: 3

### ISSUE THREAD

**Issue by Lionel-McCree** [Runsong123/AdaFit#5]
Sorry for bothering you.
When I train a multi-model, the **line 383** of **train_n_est_multi_scale.py** throws an _error train_n_est_multi_scale.py_.
The code is  `normal_loss = 0.5 * torch.norm(torch.cross(o_pred, o_target, dim=-1), p=2, dim=1).mean()`
It seems that the shape of `o_pred`([128, 3]) and `o_target`([128, 175, 3) is not matched.
But I have no idea where to change, sorry for bothering you again.
Gratefully.

**Comment by Runsong123** [comment]
> Sorry for bothering you. When I train a multi-model, the **line 383** of **train_n_est_multi_scale.py** throws an _error train_n_est_multi_scale.py_. The code is `normal_loss = 0.5 * torch.norm(torch.cross(o_pred, o_target, dim=-1), p=2, dim=1).mean()` It seems that the shape of `o_pred`([128, 3]) and `o_target`([128, 175, 3) is not matched. But I have no idea where to change, sorry for bothering you again. Gratefully.

Hi @Lionel-McCree,

Actually, I do not expect this happend. I guess the  `o_target`([128, 175, 3)  is the neightbor normal, but we should use the center normal to calculate the loss.
You might print the 'target' [variable](https://github.com/Runsong123/AdaFit/blob/main/train_n_est_multi_scale.py#L370) to check if the 'target' contains the center normals.

Best,
Runsong

**Comment by Lionel-McCree** [comment]
Thanks, I notice that this error just occurs during computing **test loss**.
I change `target = data[2:-2]` to `target = data[1:-2]`  before ** computing test loss** code block and then it can run correctly.I don't know whether it's correct for computing test loss.Anyway I use the same dataset and same parammeters as yours, and it has no influence on training process.
Thanks for your response!

**Comment by Runsong123** [comment]
> Thanks, I notice that this error just occurs during computing **test loss**. I change `target = data[2:-2]` to `target = data[1:-2]` before ** computing test loss** code block and then it can run correctly.I don't know whether it's correct for computing test loss.Anyway I use the same dataset and same parammeters as yours, and it has no influence on training process. Thanks for your response!

It's hard to judge the correctness, hhh. 
But I suggest you to use the evaluate code to calculate the metric for the test dataset.

Best,
Runsong
